# Generated by Django 5.2.3 on 2025-07-03 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="advuser",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                validators=[
                    django.core.validators.EmailValidator(message="Invalid email")
                ],
            ),
        ),
        migrations.AlterField(
            model_name="magazine",
            name="title",
            field=models.CharField(
                error_messages={"invalid": "Incorrectly name"}, max_length=30
            ),
        ),
    ]
