# Generated by Django 5.2.3 on 2025-09-20 19:45
from django.contrib.postgres.operations import (
    CreateExtension,
    BtreeGistExtension,
    TrigramExtension,
)
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        CreateExtension(name="hstore"),
        BtreeGistExtension(),
        TrigramExtension(),
    ]
