# Generated by Django 5.2.3 on 2025-09-19 14:13

import datetime
import django.contrib.postgres.fields.hstore
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_pgsproject2_pgsroomreserving_pgsrubric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pgsproject2",
            name="platforms",
            field=django.contrib.postgres.fields.hstore.HStoreField(
                validators=[
                    django.contrib.postgres.validators.KeysValidator(
                        ("client", "server"), strict=True
                    )
                ],
                verbose_name="Использование платформы",
            ),
        ),
        migrations.AlterField(
            model_name="pgsroomreserving",
            name="reserving",
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(
                validators=[
                    django.contrib.postgres.validators.RangeMinValueValidator(
                        limit_value=datetime.datetime(2000, 1, 1, 0, 0)
                    ),
                    django.contrib.postgres.validators.RangeMaxValueValidator(
                        limit_value=datetime.datetime(3000, 1, 1, 0, 0)
                    ),
                ],
                verbose_name="Время резервирования",
            ),
        ),
    ]
