# Generated by Django 5.2.3 on 2025-07-03 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_advuser_email_alter_magazine_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="bb",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bb",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bb",
            name="rubric",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="app.rubric",
            ),
        ),
        migrations.AddField(
            model_name="bb",
            name="title",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="rubric",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
