# Generated by Django 5.2.3 on 2025-07-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_bb_content_bb_price_bb_rubric_bb_title_rubric_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="title",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterOrderWithRespectTo(
            name="board",
            order_with_respect_to="rubric",
        ),
    ]
