# Generated by Django 5.2.3 on 2026-02-19 13:51

import app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_pgsproject2_pgsroomreserving_pgsrubric"),
    ]

    operations = [
        migrations.CreateModel(
            name="Img",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        upload_to=app.utils.get_timestamp_path,
                        verbose_name="Изображение",
                    ),
                ),
                ("desc", models.TextField(verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
    ]
