# Generated by Django 5.2.3 on 2026-02-20 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_img"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "permissions": [("hide_comments", "Можно скрывать комментарии")],
            },
        ),
    ]
