# Generated by Django 5.2.3 on 2025-07-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_board_title_alter_board_order_with_respect_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bb",
            name="kind3",
            field=models.SmallIntegerField(
                blank=True, choices=[(1, "Buy"), (2, "Sell"), (3, "Trade")], default=2
            ),
        ),
    ]
