# Generated by Django 5.2.3 on 2025-07-04 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_bb_kind3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bb",
            name="content",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="bb",
            name="rubric",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="app.rubric",
            ),
        ),
    ]
