# Generated by Django 5.2.3 on 2026-02-24 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_comment_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdvUser",
        ),
    ]
