# Generated by Django 5.2.3 on 2026-02-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_delete_advuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="magazine",
            name="content",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
