# Generated by Django 5.2.3 on 2025-07-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_bb_content_alter_bb_rubric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bb",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
