# Generated by Django 5.2.3 on 2025-07-04 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_bb_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bb",
            name="rubric",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entries",
                to="app.rubric",
            ),
        ),
    ]
