# Generated by Django 5.2.3 on 2025-07-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_bb_rubric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="spares",
            field=models.ManyToManyField(related_name="machines", to="app.spare"),
        ),
    ]
