# Generated by Django 5.2.3 on 2026-02-24 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_spare2_machine2"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Spare2",
        ),
    ]
