# Generated by Django 5.2.3 on 2025-07-04 17:06

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_machine_spares"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="rubric",
            field=models.ForeignKey(
                limit_choices_to={"show": True},
                on_delete=models.SET(app.models.Rubric.get_first_rubric),
                related_query_name="entry",
                to="app.rubric",
            ),
        ),
    ]
