# Generated by Django 5.2.3 on 2025-07-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_board_rubric"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
