# Generated by Django 5.2.3 on 2025-08-18 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_board_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bb",
            name="rubric",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entries",
                to="app.rubric",
            ),
        ),
    ]
