# Generated by Django 5.2.3 on 2025-08-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_bb_rubric"),
    ]

    operations = [
        migrations.AddField(
            model_name="bb",
            name="published",
            field=models.DateField(blank=True, null=True),
        ),
    ]
