# Generated by Django 5.2.3 on 2025-08-20 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_bb_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bb",
            name="published",
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
