# Generated by Django 5.2.3 on 2025-08-20 19:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_alter_bb_published"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bb",
            name="published",
        ),
        migrations.AddField(
            model_name="bb",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="bb",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
