# Generated by Django 5.2.3 on 2025-08-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_remove_bb_published_bb_created_at_bb_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rubric",
            options={"ordering": ("order", "name")},
        ),
        migrations.AddField(
            model_name="rubric",
            name="order",
            field=models.SmallIntegerField(db_index=True, default=0),
        ),
    ]
