# Generated by Django 5.2.3 on 2025-08-29 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_alter_rubric_options_rubric_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuperRubric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="rubric",
            name="super_rubric",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="super_rubric",
                to="app.superrubric",
            ),
        ),
    ]
