# Generated by Django 5.2.3 on 2025-08-31 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_superrubric_rubric_super_rubric"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machine",
            name="spares",
        ),
        migrations.CreateModel(
            name="Kit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField()),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.machine"
                    ),
                ),
                (
                    "spare",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.spare"
                    ),
                ),
            ],
        ),
    ]
