# Generated by Django 5.2.3 on 2025-08-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_remove_machine_spares_kit"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="spares",
            field=models.ManyToManyField(
                through="app.Kit", through_fields=("machine", "spare"), to="app.spare"
            ),
        ),
    ]
