# Generated by Django 5.2.3 on 2025-09-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_revrubric_privatemessage1"),
    ]

    operations = [
        migrations.CreateModel(
            name="RubricManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
