# Generated by Django 5.2.3 on 2025-09-05 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_rubricmanager"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RubricManager",
        ),
    ]
